# Generated by Django 4.0.9 on 2023-02-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0003_photo_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='depth_file',
            new_name='blured_file',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='labels',
        ),
        migrations.AddField(
            model_name='photo',
            name='labels_len',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='photo',
            name='segmentation',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
